### ISSUE TITLE
DNB-link on careerpage gives 404 error

### ISSUE THREAD

**Issue by teatimes** [dotkom/onlineweb4#1886] opened 2017-09-02 16:23 UTC
## What kind of an issue is this?

- [x] Bug report

## What is the expected behaviour?
Go to dnb's homepage.

## What is the current behaviour?
404 error. Page not found

## How do you reproduce this problem? 
Click on the link.

**Comment by sklirg** [comment] 2017-09-02 16:25
This is the cause of the bug reported in #1718. Closing this in favor of that :-)

**Closed by sklirg** 2017-09-02 16:25 UTC
Labels: Priority: High, Type: Bug
