### ISSUE TITLE
Editing wiki design flaws

### ISSUE THREAD

**Issue by nornes** [dotKom/onlineweb4#1411] opened 2016-02-05 13:15 UTC
When editing a wiki document the editing buttons over the content area are partially covered by the content area, and the buttons underneath looks weird. 
Also there has been a request to expand the content editing area to the left as well as to the right.

**Comment by OptimusCrime** [comment] 2016-02-05 14:04
I can take a look at this at the next meeting

**Comment by cXhristian** [comment] 2016-02-05 14:18
>When editing a wiki document the editing buttons over the content area are partially covered by the content area

Not sure what you mean by this. Could you provide a screenshot?

> the buttons underneath looks weird. 

Yep, should be fixed.

>there has been a request to expand the content editing area to the left as well as to the right.

Expanding to the left is not part of the CSS spec afaik. Could be done with custom code, but imo that's not a good idea.
I think a better solution would be to add a full width editing mode.

**Comment by OptimusCrime** [comment] 2016-02-05 16:23
@cXhristian I think add possibility to resize horizontally is what they mean.

**Comment by cXhristian** [comment] 2016-02-05 17:45
That already works though?

**Comment by OptimusCrime** [comment] 2016-02-10 19:48
I'm closing this as a wontfix. These changes are caused by django-wiki. I think they should be solved there too.

**Closed by OptimusCrime** 2016-02-10 19:48 UTC
