### ISSUE TITLE
Seniorkom missing from "add verv" in user profile.

### ISSUE THREAD

**Issue by kongshem** [dotKom/onlineweb4#1575] opened 2016-05-11 15:41 UTC
The dropdown box containing the different committees is missing "seniorkom".
![issue](https://cloud.githubusercontent.com/assets/1532384/15186992/8bd389aa-179f-11e6-9d2e-32315351a7f3.png)

**Comment by sklirg** [comment] 2016-05-11 15:42
Duplicate of https://github.com/dotKom/onlineweb4/issues/1346.

We're aware of the problem, and the mentioned issue contains reasoning for why.

**Closed by sklirg** 2016-05-11 15:42 UTC
