### ISSUE TITLE
Searching the wiki gives multiple identical results

### ISSUE THREAD

**Issue by sverrejb** [dotKom/onlineweb4#1775] opened 2016-11-16 19:55 UTC
As far as I can tell, searching for something in the wiki, e.g "Arvid Holme", returns multiple results that all lead to the same page. One could think that multiple revisions could be returned, but this does not seem to be the case.

**Comment by OptimusCrime** [comment] 2016-11-16 21:09
Not able to reproduce. I searched for "Arvid Holme" and it returned 19 results. As far as I can see they all link to different wiki entries (no duplicate revisions).

Could you come with some examples?

**Comment by sverrejb** [comment] 2016-11-16 22:12
https://online.ntnu.no/wiki/_search/?q=Arvid+Holme gives me 752 results when logged in.
When not logged in, I get 5 results.
https://www.dropbox.com/s/fa1tbwsigdikriy/Screenshot%202016-11-16%2023.07.27.png?dl=0

**Comment by sklirg** [comment] 2016-11-21 12:21
This is a duplicate of #1655. 

I think this is a bug with [django-wiki/django-wiki](https://github.com/django-wiki/django-wiki), not [dotKom/onlineweb4](..).

**Closed by sklirg** 2016-11-21 12:21 UTC
