### ISSUE TITLE
Sponsor logo in wrong location in Edge

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#1820] opened 2017-03-07 13:22 UTC
## What kind of an issue is this?

- [x] Bug report

## What is the expected behaviour?

The sponsor logo is in the top bar.

## What is the current behaviour?

See attached screen shot. The logo is over the "export" button. This makes it so if you try to click the export button, you go to the link of the sponsor logo.

## How do you reproduce this problem? 

Opened an event page on online.ntnu.no in Edge.

## Other information

Screenshot from Edge:
![image](https://cloud.githubusercontent.com/assets/5422571/23654384/b0de1a94-0330-11e7-8590-1649efb60610.png)

**Comment by oleast** [comment] 2018-02-01 11:09
Cannot reproduce bug with Edge v. `41.16299.15.0` on Windows.

Tested resolutions:
`800x480`, `1024x768`, `1280x720`, `1280x800`, `1366x768`, `1920x1080`, `2560x1440`.
*also tested at half horizontal resolution for each of them.*

Tested on Edge for Android as well.

Probably fixed by changes in Microsoft Edge or by new sponsor logo.

_Closing._

**Closed by oleast** 2018-02-01 11:09 UTC
Labels: Type: Bug, Type: UI
