### ISSUE TITLE
Update committee abbreviation

### ISSUE THREAD

**Issue by tePose** [dotKom/onlineweb4#1537] opened 2016-04-22 10:29 UTC
Following the updated Online statute, all *Kom abbreviations should be replaced with *kom. This is especially visible on "chunks", but also on the wiki pages.

**Comment by sklirg** [comment] 2016-04-22 10:38
This is a duplicate of #1533. Closing this one in favour of #1533.

**Closed by sklirg** 2016-04-22 10:38 UTC
