### ISSUE TITLE
Online logoen er borte

### ISSUE THREAD

**Issue by Nicolaad** [dotkom/onlineweb4#2395] opened 2019-11-19 14:07 UTC
**Describe the bug**
Online logoen øverst i venstre hjørne er borte, og i dens fravær er det en klokke som går feil vei.

**To Reproduce**
1. klikk på søkerfeltet i din favoritt browser
2. skriv inn "https://online.ntnu.no/"
3. trykk knappen '↵' på ditt tastatur
4. Se øverst i venstre hjørne
5. Se at online logoen ikke er der :( 

**Expected behavior**
https://imgur.com/a/2DJlED3

**Screenshots**
https://imgur.com/a/9Nt5vRK

**Desktop:**
 - OS: Ubuntu
 - Browser: Firefox

**Additional context**
Hjelp - jeg savner Online logoen

**Comment by kharann** [comment] 2019-11-19 14:10
Yep yep, we will have a look

**Comment by FredrikAugust** [comment] 2019-11-20 19:19
Any updates on this. The bug is still present.

**Comment by kharann** [comment] 2019-11-20 19:20
I tried to solve this issue, however it turns it is wayyy too complex than i expected. I will assign an expert to help us solve this issue.

**Comment by blauks** [comment] 2019-11-22 11:51
Seems like the issue is fixed now.
![image](https://user-images.githubusercontent.com/33070123/69423580-bda75580-0d26-11ea-9642-0de32da99674.png)
Good job everyone!

**Closed** 2019-11-22 16:16 UTC
Labels: Priority: High, Priority: Low
